name: Build and upload
on:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: windows-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: Build client
        run: dotnet build --configuration Release

      - name: Upload to Github Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Client
          path: ./Build/Client/Release
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Github Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Server
          path: ./Build/Server/Release
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Github Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: LibraryEditor
          path: ./Build/Server Tools/LibraryEditor/Release
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Github Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: LibraryViewer
          path: ./Build/Server Tools/LibraryViewer/Release
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}