// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Database;

#nullable disable

namespace Server.Library.Database.Migrations
{
    [DbContext(typeof(Mir2DbContext))]
    [Migration("20260119013108_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Server.Database.PersistenceModels.AccountEntity", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AdminAccount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BanReason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Banned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreationIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Credit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpandedStorageExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasExpandedStorage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequirePasswordChange")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("SecretAnswer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretQuestion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("StorageSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Index");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.AccountStorageItemEntity", b =>
                {
                    b.Property<int>("AccountIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserItemId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("AccountIndex", "SlotIndex");

                    b.HasIndex("UserItemId")
                        .IsUnique();

                    b.ToTable("AccountStorageItems", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.AuctionEntity", b =>
                {
                    b.Property<string>("AuctionId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConsignmentDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("CurrentBid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentBuyerIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Expired")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SellerIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Sold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserItemId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("AuctionId");

                    b.HasIndex("CurrentBuyerIndex");

                    b.HasIndex("SellerIndex");

                    b.HasIndex("UserItemId")
                        .IsUnique();

                    b.ToTable("Auctions", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterBuffEntity", b =>
                {
                    b.Property<int>("CharacterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("CharacterIndex", "SlotIndex");

                    b.ToTable("CharacterBuffs", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterCompletedQuestEntity", b =>
                {
                    b.Property<int>("CharacterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterIndex", "QuestIndex");

                    b.ToTable("CharacterCompletedQuests", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterCurrentRefineItemEntity", b =>
                {
                    b.Property<int>("CharacterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserItemId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterIndex");

                    b.HasIndex("UserItemId")
                        .IsUnique();

                    b.ToTable("CharacterCurrentRefineItems", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterEntity", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowGroup")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowObserve")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowTrade")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AttackMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BanReason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Banned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BindLocationX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BindLocationY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BindMapIndex")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreationIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CrossHalfMoon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentHeroIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentLocationX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentLocationY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentMapIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DeleteDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DoubleSlash")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentSize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FlagsData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildIndex")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Hair")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HalfMoon")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("HeroBehaviour")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HeroSpawned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventorySize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMentor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLogoutDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Married")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MarriedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumHeroCount")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MentalState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mentor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MentorDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("MentorExp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("PearlCount")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("PetMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PkPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestInventorySize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RefineTimeRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Thrusting")
                        .HasColumnType("INTEGER");

                    b.HasKey("Index");

                    b.HasIndex("AccountIndex");

                    b.HasIndex("Name");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterEquipmentItemEntity", b =>
                {
                    b.Property<int>("CharacterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserItemId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterIndex", "SlotIndex");

                    b.HasIndex("UserItemId")
                        .IsUnique();

                    b.ToTable("CharacterEquipmentItems", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterFriendEntity", b =>
                {
                    b.Property<int>("CharacterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FriendIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Blocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterIndex", "FriendIndex");

                    b.ToTable("CharacterFriends", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterGsPurchaseEntity", b =>
                {
                    b.Property<int>("CharacterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterIndex", "ItemKey");

                    b.ToTable("CharacterGspurchases", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterHeroSlotEntity", b =>
                {
                    b.Property<int>("CharacterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterIndex", "SlotIndex");

                    b.HasIndex("HeroIndex");

                    b.HasIndex("CharacterIndex", "HeroIndex")
                        .IsUnique();

                    b.ToTable("CharacterHeroSlots", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterIntelligentCreatureEntity", b =>
                {
                    b.Property<int>("CharacterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("CharacterIndex", "SlotIndex");

                    b.ToTable("CharacterIntelligentCreatures", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterInventoryItemEntity", b =>
                {
                    b.Property<int>("CharacterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserItemId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterIndex", "SlotIndex");

                    b.HasIndex("UserItemId")
                        .IsUnique();

                    b.ToTable("CharacterInventoryItems", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterMagicEntity", b =>
                {
                    b.Property<int>("CharacterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Spell")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CastTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTempSpell")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Key")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterIndex", "Spell");

                    b.ToTable("CharacterMagics", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterPetEntity", b =>
                {
                    b.Property<int>("CharacterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPetLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonsterIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterIndex", "SlotIndex");

                    b.ToTable("CharacterPets", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterQuestInventoryItemEntity", b =>
                {
                    b.Property<int>("CharacterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserItemId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterIndex", "SlotIndex");

                    b.HasIndex("UserItemId")
                        .IsUnique();

                    b.ToTable("CharacterQuestInventoryItems", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterQuestProgressEntity", b =>
                {
                    b.Property<int>("CharacterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestIndex")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("CharacterIndex", "QuestIndex");

                    b.ToTable("CharacterQuestProgress", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterRentedItemEntity", b =>
                {
                    b.Property<int>("CharacterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("CharacterIndex", "SlotIndex");

                    b.ToTable("CharacterRentedItems", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.ConquestArcherStateEntity", b =>
                {
                    b.Property<int>("ConquestIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Alive")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConquestIndex", "Index");

                    b.ToTable("ConquestArchers", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.ConquestGateStateEntity", b =>
                {
                    b.Property<int>("ConquestIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConquestIndex", "Index");

                    b.ToTable("ConquestGates", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.ConquestInfoEntity", b =>
                {
                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Index");

                    b.ToTable("ConquestInfos", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.ConquestSiegeStateEntity", b =>
                {
                    b.Property<int>("ConquestIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConquestIndex", "Index");

                    b.ToTable("ConquestSieges", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.ConquestStateEntity", b =>
                {
                    b.Property<int>("ConquestIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GoldStorage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NpcRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Owner")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConquestIndex");

                    b.HasIndex("Owner");

                    b.ToTable("Conquests", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.ConquestWallStateEntity", b =>
                {
                    b.Property<int>("ConquestIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConquestIndex", "Index");

                    b.ToTable("ConquestWalls", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.DbMetaEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("ConquestIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameshopIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonsterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NextAuctionId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("NextCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextGuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextHeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NextMailId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NextUserItemId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("NpcIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RespawnIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DbMeta", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.DragonInfoStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("DragonInfoState", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.GameShopItemEntity", b =>
                {
                    b.Property<int>("GIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("GIndex");

                    b.ToTable("GameShopItems", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.GameshopLogEntryEntity", b =>
                {
                    b.Property<int>("ItemKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemKey");

                    b.ToTable("GameshopLog", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.GtMapEntity", b =>
                {
                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Index");

                    b.ToTable("GtMaps", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.GuildBuffEntity", b =>
                {
                    b.Property<int>("GuildIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuffIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveTimeRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildIndex", "BuffIndex");

                    b.ToTable("GuildBuffs", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.GuildEntity", b =>
                {
                    b.Property<int>("GuildIndex")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlagColourArgb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlagImage")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GtBegin")
                        .HasColumnType("TEXT");

                    b.Property<int>("GtIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GtKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GtPrice")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GtRent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastVoteAttempt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SparePoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Votes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Voting")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildIndex");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Guilds", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.GuildMemberEntity", b =>
                {
                    b.Property<int>("GuildIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RankIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasVoted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Online")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildIndex", "RankIndex", "MemberIndex");

                    b.HasIndex("GuildIndex", "Id");

                    b.ToTable("GuildMembers", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.GuildNoticeEntity", b =>
                {
                    b.Property<int>("GuildIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("GuildIndex", "LineIndex");

                    b.ToTable("GuildNotices", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.GuildRankEntity", b =>
                {
                    b.Property<int>("GuildIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RankIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Options")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildIndex", "RankIndex");

                    b.ToTable("GuildRanks", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.GuildStorageItemEntity", b =>
                {
                    b.Property<int>("GuildIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserItemId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("GuildIndex", "SlotIndex");

                    b.HasIndex("UserItemId")
                        .IsUnique();

                    b.ToTable("GuildStorageItems", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.HeroEntity", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AutoHpPercent")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AutoMpPercent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoPot")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeleteDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentSize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Grade")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Hair")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HpItemIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventorySize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MpItemIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SealCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Index");

                    b.HasIndex("Name");

                    b.ToTable("Heroes", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.HeroEquipmentItemEntity", b =>
                {
                    b.Property<int>("HeroIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserItemId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("HeroIndex", "SlotIndex");

                    b.HasIndex("UserItemId")
                        .IsUnique();

                    b.ToTable("HeroEquipmentItems", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.HeroInventoryItemEntity", b =>
                {
                    b.Property<int>("HeroIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserItemId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("HeroIndex", "SlotIndex");

                    b.HasIndex("UserItemId")
                        .IsUnique();

                    b.ToTable("HeroInventoryItems", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.HeroMagicEntity", b =>
                {
                    b.Property<int>("HeroIndex")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Spell")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CastTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTempSpell")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Key")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("HeroIndex", "Spell");

                    b.ToTable("HeroMagics", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.ItemInfoEntity", b =>
                {
                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Index");

                    b.ToTable("ItemInfos", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.MagicInfoEntity", b =>
                {
                    b.Property<byte>("Spell")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Spell");

                    b.ToTable("MagicInfos", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.MailEntity", b =>
                {
                    b.Property<string>("MailId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanReply")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Collected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOpened")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("TEXT");

                    b.Property<long>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Locked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipientIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("MailId");

                    b.HasIndex("RecipientIndex");

                    b.ToTable("Mail", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.MailItemEntity", b =>
                {
                    b.Property<string>("MailId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserItemId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("MailId", "SlotIndex");

                    b.HasIndex("UserItemId")
                        .IsUnique();

                    b.ToTable("MailItems", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.MapInfoEntity", b =>
                {
                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Index");

                    b.ToTable("MapInfos", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.MonsterInfoEntity", b =>
                {
                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Index");

                    b.ToTable("MonsterInfos", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.NpcInfoEntity", b =>
                {
                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Index");

                    b.ToTable("NpcInfos", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.NpcUsedGoodEntity", b =>
                {
                    b.Property<int>("NpcIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserItemId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("NpcIndex", "SlotIndex");

                    b.HasIndex("NpcIndex");

                    b.HasIndex("UserItemId")
                        .IsUnique();

                    b.ToTable("NpcUsedGoods", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.QuestInfoEntity", b =>
                {
                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Index");

                    b.ToTable("QuestInfos", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.RespawnSaveEntity", b =>
                {
                    b.Property<int>("RespawnIndex")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NextSpawnTick")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Spawned")
                        .HasColumnType("INTEGER");

                    b.HasKey("RespawnIndex");

                    b.HasIndex("NextSpawnTick");

                    b.ToTable("RespawnSaves", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.RespawnTimerStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("RespawnTimerState", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.UserItemEntity", b =>
                {
                    b.Property<string>("UserItemId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AddedStatsData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("AwakeData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<ushort>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("CurrentDura")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cursed")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ExpireInfoData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<ushort>("GemCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GmMade")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Identified")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShopItem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemIndex")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("MaxDura")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("RefineAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RefineSuccessChance")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("RefinedValue")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RentalInformationData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SealedInfoData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("SlotsLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoulBoundId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeddingRing")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserItemId");

                    b.HasIndex("ItemIndex");

                    b.ToTable("UserItems", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.UserItemSlotEntity", b =>
                {
                    b.Property<string>("ParentUserItemId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChildUserItemId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ParentUserItemId", "SlotIndex");

                    b.HasIndex("ChildUserItemId")
                        .IsUnique();

                    b.ToTable("UserItemSlots", (string)null);
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.AccountStorageItemEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Database.PersistenceModels.UserItemEntity", null)
                        .WithMany()
                        .HasForeignKey("UserItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.AuctionEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CurrentBuyerIndex")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Database.PersistenceModels.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("SellerIndex")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Database.PersistenceModels.UserItemEntity", null)
                        .WithMany()
                        .HasForeignKey("UserItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterBuffEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterCompletedQuestEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterCurrentRefineItemEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Database.PersistenceModels.UserItemEntity", null)
                        .WithMany()
                        .HasForeignKey("UserItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterEquipmentItemEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Database.PersistenceModels.UserItemEntity", null)
                        .WithMany()
                        .HasForeignKey("UserItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterFriendEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterGsPurchaseEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterHeroSlotEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Database.PersistenceModels.HeroEntity", null)
                        .WithMany()
                        .HasForeignKey("HeroIndex")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterIntelligentCreatureEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterInventoryItemEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Database.PersistenceModels.UserItemEntity", null)
                        .WithMany()
                        .HasForeignKey("UserItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterMagicEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterPetEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterQuestInventoryItemEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Database.PersistenceModels.UserItemEntity", null)
                        .WithMany()
                        .HasForeignKey("UserItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterQuestProgressEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.CharacterRentedItemEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.ConquestArcherStateEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.ConquestStateEntity", null)
                        .WithMany()
                        .HasForeignKey("ConquestIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.ConquestGateStateEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.ConquestStateEntity", null)
                        .WithMany()
                        .HasForeignKey("ConquestIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.ConquestSiegeStateEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.ConquestStateEntity", null)
                        .WithMany()
                        .HasForeignKey("ConquestIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.ConquestWallStateEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.ConquestStateEntity", null)
                        .WithMany()
                        .HasForeignKey("ConquestIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.GuildBuffEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.GuildEntity", null)
                        .WithMany()
                        .HasForeignKey("GuildIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.GuildMemberEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.GuildEntity", null)
                        .WithMany()
                        .HasForeignKey("GuildIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.GuildNoticeEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.GuildEntity", null)
                        .WithMany()
                        .HasForeignKey("GuildIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.GuildRankEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.GuildEntity", null)
                        .WithMany()
                        .HasForeignKey("GuildIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.GuildStorageItemEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.GuildEntity", null)
                        .WithMany()
                        .HasForeignKey("GuildIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Database.PersistenceModels.UserItemEntity", null)
                        .WithMany()
                        .HasForeignKey("UserItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.HeroEquipmentItemEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.HeroEntity", null)
                        .WithMany()
                        .HasForeignKey("HeroIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Database.PersistenceModels.UserItemEntity", null)
                        .WithMany()
                        .HasForeignKey("UserItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.HeroInventoryItemEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.HeroEntity", null)
                        .WithMany()
                        .HasForeignKey("HeroIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Database.PersistenceModels.UserItemEntity", null)
                        .WithMany()
                        .HasForeignKey("UserItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.HeroMagicEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.HeroEntity", null)
                        .WithMany()
                        .HasForeignKey("HeroIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.MailEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("RecipientIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.MailItemEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.MailEntity", null)
                        .WithMany()
                        .HasForeignKey("MailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Database.PersistenceModels.UserItemEntity", null)
                        .WithMany()
                        .HasForeignKey("UserItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.NpcUsedGoodEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.UserItemEntity", null)
                        .WithMany()
                        .HasForeignKey("UserItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Database.PersistenceModels.UserItemSlotEntity", b =>
                {
                    b.HasOne("Server.Database.PersistenceModels.UserItemEntity", null)
                        .WithMany()
                        .HasForeignKey("ChildUserItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Database.PersistenceModels.UserItemEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentUserItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
